USE [master]
GO

/****** Object:  Database [HuntingApp]    Script Date: 3/1/2019 16:33:19 ******/
CREATE DATABASE [HuntingApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HuntingApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\HuntingApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HuntingApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\HuntingApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [HuntingApp] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HuntingApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HuntingApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HuntingApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HuntingApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HuntingApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HuntingApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [HuntingApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HuntingApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HuntingApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HuntingApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HuntingApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HuntingApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HuntingApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HuntingApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HuntingApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HuntingApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HuntingApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HuntingApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HuntingApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HuntingApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HuntingApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HuntingApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HuntingApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HuntingApp] SET RECOVERY FULL 
GO

ALTER DATABASE [HuntingApp] SET  MULTI_USER 
GO

ALTER DATABASE [HuntingApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HuntingApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HuntingApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HuntingApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HuntingApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HuntingApp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HuntingApp] SET  READ_WRITE 
GO

