USE [master]
GO

/****** Object:  Database [HuntingAppDB]    Script Date: 3/1/2019 16:33:19 ******/
CREATE DATABASE [HuntingAppDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HuntingAppDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\HuntingAppDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HuntingAppDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\HuntingAppDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [HuntingAppDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HuntingAppDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HuntingAppDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HuntingAppDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HuntingAppDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HuntingAppDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HuntingAppDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HuntingAppDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HuntingAppDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HuntingAppDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HuntingAppDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HuntingAppDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HuntingAppDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HuntingAppDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HuntingAppDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HuntingAppDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HuntingAppDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HuntingAppDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HuntingAppDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HuntingAppDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HuntingAppDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HuntingAppDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HuntingAppDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HuntingAppDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HuntingAppDB] SET RECOVERY FULL 
GO

ALTER DATABASE [HuntingAppDB] SET  MULTI_USER 
GO

ALTER DATABASE [HuntingAppDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HuntingAppDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HuntingAppDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HuntingAppDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HuntingAppDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HuntingAppDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HuntingAppDB] SET  READ_WRITE 
GO

